version: 2.1

orbs:
  node: circleci/node@6.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:22.14.0
    working_directory: ~/chunk-demo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          cache-key: 'npm-cache-{{ checksum "package-lock.json" }}'
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test

workflows:
  chunk-demo-validation:
    jobs:
      - build-and-test
